[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[pypi-dependencies]
pyshtransform = { path = ".", editable = true }

[tasks]

[dependencies]
numpy = ">=2.3.3,<3"
scipy = ">=1.16.2,<2"
xarray = ">=2025.10.1,<2026"
dask = ">=2025.10.0,<2026"
h5netcdf = ">=1.7.3,<2"
pytest = ">=8.4.2,<9"
ruff = ">=0.14.1,<0.15"
pixi-pycharm = ">=0.0.9,<0.0.10"
rich = ">=14.2.0,<15"

