[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[pypi-dependencies]
pyshtransform = { path = ".", editable = true }

[tasks]
lint = "ruff check"
format = "ruff format --config \"lint.ignore = ['COM812']\""
static-an = "mypy src/"
tests = "pytest -vs"
gen-api-doc = "sphinx-apidoc -f -o docs/source/api/ src/"
clean-doc = "sphinx-build -M clean docs/source/ docs/build/"
gen-doc = "sphinx-build -M html docs/source/ docs/build/"

[dependencies]
dask = ">=2025.10.0,<2026"
h5netcdf = ">=1.7.3,<2"
ipykernel = ">=7.1.0,<8"
mypy = ">=1.18.2,<2"
m2r2 = ">=0.3.4,<0.4"
numpy = ">=2.3.3,<3"
pixi-pycharm = ">=0.0.9,<0.0.10"
pytest = ">=8.4.2,<9"
rich = ">=14.2.0,<15"
ruff = ">=0.14.1,<0.15"
scipy = ">=1.16.2,<2"
scipy-stubs = ">=1.16.2.4,<2"
sphinx = ">=8.2.3,<9"
sphinx-rtd-theme = ">=3.0.2,<4"
xarray = ">=2025.10.1,<2026"
