[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
    {name = "Alban Farchi", email = "alban.farchi@ecmwf.int"},
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "numpy",
    "scipy",
    "xarray",
]
description = "Spherical harmonics transformation in Python"
name = "pyshtransform"
readme = "README.md"
requires-python = ">= 3.11"
version = "1.1.1"
keywords = [
    "spherical harmonics",
]

[project.optional-dependencies]
dev = [
    "dask",
    "h5netcdf",
    "ipykernel",
    "mypy",
    "pytest",
    "rich",
    "ruff",
    "scipy-stubs",
]

[project.urls]
Documentation = "https://pyshtransform.readthedocs.io"
Issues = "https://github.com/aFarchi/pyshtransform/issues"
Source = "https://github.com/aFarchi/pyshtransform"

[tool.mypy]
strict = true

[tool.ruff]
exclude = [
    "docs",
]
preview = true

[tool.ruff.format]
docstring-code-format = true
quote-style = "single"

[tool.ruff.lint]
flake8-quotes.inline-quotes = "single"
pydocstyle.convention = "google"
pylint.max-args = 10
pylint.max-locals = 20
pylint.allow-magic-value-types = ["int"]
select = ["ALL"]
ignore = [
    # no copyright on files
    "CPY001",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    # no docstring
    "D104",
]
"tests/*" = [
    # no annotations
    "ANN",
    # no docstrings
    "D",
    # no __init__.py
    "INP001",
    # use print
    "T201",

]

[tool.pytest.ini_options]
console_output_style = "progress"
testpaths = [
    "tests/",
]
norecursedirs = ["data"]
filterwarnings = [
    "error",
    "ignore:invalid value encountered in divide:RuntimeWarning:dask._task_spec:759",
]
